# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1951550a5dd0b119dcc1bbeb3cdad5bd9db3058fdb994334d3985ae2d6c2e4a78e99725135022173a62c20cb7cf4c0f8ec887f3c114743d45fa0f81c1d76c181

test:
  secret_key_base: d9fea8b16c919d0a09a2cc3d750869b79505d97708386c50c2456ea0d8722cfa71fb980c839a171a5b034109778e4ce45e1790e4521a53e5430f2e60ca662fd2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
